config/routes.rb
Wishlist::Application.routes.draw do

  resources :wishes

  get "profile/edit"

  match '/friends', :to => 'friends#index'
  match '/friends/:id', :to => 'friends#show', :as => 'friend'
  match '/home',  :to => 'landing#home_page'
  match '/auth/vkontakte/callback', :to => 'landing#login'
  match '/logout', :to => 'landing#logout'
  match '/friends_whose_birthday_is_in_one_week', :to => 'friends#bdate_in_1_week', :as => 'friends_one_week'
  match '/friends_whose_birthday_is_in_two_weeks', :to => 'friends#bdate_in_2_weeks', :as => 'friends_two_weeks'
  match '/friends_whose_birthday_is_in_one_month', :to => 'friends#bdate_in_1_month', :as => 'friends_one_month'
  match '/friends_whose_birthday_is_unknown', :to => 'friends#bdate_unknown', :as => 'friends_unknown'
  match '/search', :to => 'wishes#search', :as => 'search'
  match '/new', :to => 'wishes#new'
  match '/reserve', :to => 'reserve#index', :as => 'reserve_index'
  match '/reserve/:id/add', :to => 'reserve#add_reserve', :as => 'add_reserve'
  match '/reserve/:id/delete', :to => 'reserve#delete_reserve', :as => 'delete_reserve'
  match '/local_login', :to => 'landing#local_login', :as => 'local_login'
  match '/local_login/:id', :to => 'landing#local_login_as', :as => 'local_user'

  root :to => 'landing#home_page'

end

app/models/wish.rb
# == Schema Information
#
# Table name: wishes
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  url                :string(255)
#  description        :text
#  owner_id           :integer
#  rating             :integer
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Wish < ActiveRecord::Base
  attr_accessible :image, :description, :name, :owner_id, :rating, :url

  belongs_to :owner, :class_name => 'Person'
  has_one :reservation
	default_scope :order => 'rating DESC'
  has_attached_file :image

  validates :name, :presence => true, :length => {:in => 2..50}
  validates :url, :presence => true, :format =>  {:with => /^((http|https|ftp):\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix }
  validates :owner_id, :presence =>  true
  validates :rating, :presence => true, :inclusion => {:in => 1..5}
end

app/controllers/wishes_controller.rb
# encoding: utf-8

class WishesController < ApplicationController
  before_filter :set_current_user

  protected
  def set_current_user
    if (current_user == nil)
      render 'landing/not_login'
    end
  end


  public

  def index
    @title = "All your wishes"
    @wishes = Wish.where(:owner_id => current_user.id)
  end

  def show
    #Show a single wish
    @wish = Wish.find(params[:id])
    @friend = Person.find(@wish.owner_id)
    @days_till_bday = days_till_bday(@friend)
    @title = "#{@wish.name}"
  end

  def days_till_bday(friend)
    if friend.birthday == nil then return end
    d_now = DateTime.strptime(DateTime.now.to_s[5,DateTime.now.to_s.length],'%m-%d')
    bday = DateTime.strptime(friend.birthday.to_s[5, friend.birthday.to_s.length],'%m-%d')
    if (d_now == bday)
      'сегодня'
    else
      if (bday > d_now)
        count = (bday - d_now).to_int
        '( через ' + count.to_s + ' '+ Russian.p(count,'день','дня','дней','дня') + ' )'
      else
        count = 365 - (d_now - bday).to_int
        '( через ' + count.to_s + ' '+ Russian.p(count,'день','дня','дней','дня') + ' )'
      end
    end
  end

  def new
    @title = "Add new wish"
    @wish = Wish.new
    result = params[:query]
    url_patern = /^((http|https|ftp):\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
    if result =~ url_patern
      @search_url = result
      @search_name = ""
    else
      @search_name = result
      @search_url = ""
    end

  end

  def edit
    @title = "Edit wish page"
    @wish = Wish.find(params[:id])
  end

  def create
    @wish = Wish.new(params[:wish])
    if @wish.save
      flash[:success] = "Your wish was saved successfully"
      redirect_to wishes_path
    else
      flash[:error] = "Error in wish saving"
      redirect_to new_wish_path # Временно
    end

    #Create a new wish
  end

  def update
    @wish = Wish.find(params[:id])
    if @wish.update_attributes(params[:wish])
      redirect_to wishes_path
    else
      redirect_to edit_wish_path(@wish)
    end
  end

  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy
    flash[:success] = "Your wish was delete successfully"
    redirect_to wishes_path
  end

  def search
    @title = "Search a wish"
  end


end

app/views/wishes/create.html.erb
<h1>Success!!!</h1>

app/views/wishes/edit.html.erb
<div class="row">
  <div class="col1of2">
    <div>
      <%= image_tag(@wish.image, :border => 0)  %>
    </div>
  </div>
  <div class="col1of2">
    <div class="form">
      <%=  form_for @wish, :url => {:action => "update"} do |f| %>
          <div class="mbs"><label>Название:</label><%= f.text_field :name %><!--<span id="error_name"></span>--><br></div>

          <%= render 'layouts/wish_form', :f => f %>

          <%= link_to "Удалить", wish_path(@wish),:class =>"cancel", :method => :delete %>
          <%= f.hidden_field :owner_id, :value => current_user.id %><!--<span id="error_url"></span>-->
      <% end %>
     </div>
   </div>
</div>

app/views/wishes/index.html.erb
<h3 style="background-color: #7fffd4; " ><%= flash[:success] %> </h3>
<%  if (@wishes.size != 0)  %>
<div id="container">
    <%@wishes.each do |w| %>
    <%= link_to image_tag(w.image, :border => 0, :class => 'item'), edit_wish_path(w) %>
    <% end %>
</div>
<% else %>
    <p>Список желаний пуст</p>
<% end %>

app/views/wishes/new.html.erb
<div class="row">
  <div class="col1of2">
    <div class="WishNewImage">
      <%= image_tag("NoImage.png", :border => 0) %>
    </div>
   </div>
  <div class="col1of2">
    <h2 style="background-color: #ff0000; " ><%= flash[:error] %> </h2>
    <div class="form">
     <%=  form_for @wish, :url => {:action => "create"} do |f| %>
      <div class="mbs"><label>Название:</label><%= f.text_field :name, :value => @search_name.to_s %><!--<span id="error_name"></span>--><br></div>
      <div class="mbs"><label>Изображение:</label><%= f.file_field :image %><br></div>

          <%= render 'layouts/wish_form', :f => f %>

      <%= link_to "Отмена", search_path, :class => "cancel" %>
      <%= f.hidden_field :owner_id, :value => current_user.id %><!--<span id="error_url"></span>-->
      <% end %>
    </div>
  </div>
</div>

app/views/wishes/result.erb
<p>This is your query</p>
<%=  @result %>

app/views/wishes/search.html.erb
<p class="h1 searchText">Чтобы добавить желание введите название или URL</p>
<div class="row pole">
<%= form_tag(new_wish_path,  :method => :get) do %>
    <%= text_field_tag(:query, nil, :id => "searchField") %>
    <%= submit_tag("", :class => "searchButton") %>
</div>
<% end %>

app/views/wishes/show.html.erb
<%= image_tag(@friend.vk_avatar_url, :class => 'FriendAvatar')%>
<div class="FriendInformation">

  <%= render 'layouts/friend_info'  %>

  <br /><br />
  <div class="row">
    <div class="col1of2">
      <div>
        <p>
          <%= image_tag(@wish.image, :border => 0)  %>
        </p>
      </div>
    </div>
    <div class="col1of2">
      <div class="form">
        <%=  form_for @wish, :url => {:action => "update"} do |f| %>
            <div class="mbs"><label>Название:</label><%= f.text_field :name %><!--<span id="error_name"></span>--><br></div>

            <div class="mbs"><label>Хочу на ... </label><div class="stars">
              <%= f.radio_button :rating, "1", :class => "star", :checked => "checked" %>
              <%= f.radio_button :rating, "2", :class => "star" %>
              <%= f.radio_button :rating, "3", :class => "star" %>
              <%= f.radio_button :rating, "4", :class => "star" %>
              <%= f.radio_button :rating, "5", :class => "star" %></div>
              <!--<span id="error_rating"></span>--><br></div>
            <div class="mbs"><label>URL</label><%=  f.text_field :url %><!--<span id="error_url"></span>--><br></div>
            <div class="mbs"><label>Описание</label><%=  f.text_area :description %><br></div>
            <br />
            <% if Reservation.find_by_wish_id(@wish.id) == nil %>
                <%= link_to "Зарезервировать", add_reserve_path(@wish) %>
            <% else %>
                <%= link_to "Отмена резерва", delete_reserve_path(@wish) %>
            <% end %>

            <%= f.hidden_field :owner_id, :value => Person.find(@wish.owner_id).name %><!--<span id="error_url"></span>-->
        <% end %>


      </div>
    </div>
  </div>
 </div>