config/routes.rb
Wishlist::Application.routes.draw do

  resources :wishes

  get "profile/edit"

  match '/friends', :to => 'friends#index'
  match '/friends/:id', :to => 'friends#show', :as => 'friend'
  match '/home',  :to => 'landing#home_page'
  match '/auth/vkontakte/callback', :to => 'landing#login'
  match '/logout', :to => 'landing#logout'
  match '/friends_whose_birthday_is_in_one_week', :to => 'friends#bdate_in_1_week', :as => 'friends_one_week'
  match '/friends_whose_birthday_is_in_two_weeks', :to => 'friends#bdate_in_2_weeks', :as => 'friends_two_weeks'
  match '/friends_whose_birthday_is_in_one_month', :to => 'friends#bdate_in_1_month', :as => 'friends_one_month'
  match '/friends_whose_birthday_is_unknown', :to => 'friends#bdate_unknown', :as => 'friends_unknown'
  match '/search', :to => 'wishes#search', :as => 'search'
  match '/new', :to => 'wishes#new'
  match '/reserve', :to => 'reserve#index', :as => 'reserve_index'
  match '/reserve/:id/add', :to => 'reserve#add_reserve', :as => 'add_reserve'
  match '/reserve/:id/delete', :to => 'reserve#delete_reserve', :as => 'delete_reserve'
  match '/local_login', :to => 'landing#local_login', :as => 'local_login'
  match '/local_login/:id', :to => 'landing#local_login_as', :as => 'local_user'

  root :to => 'landing#home_page'

end

app/controllers/friends_controller.rb
# encoding: utf-8
class FriendsController < ApplicationController
  before_filter :set_current_user
  before_filter :correct_friend, :only => :show

  protected

  def set_current_user
    if (current_user == nil)
      render 'landing/not_login'
    end
  end

  def correct_friend
    friend = current_user.friends.where(id: params[:id]).first
    redirect_to friends_path if friend == nil
  end

  public

  def index
    friends = current_user.friends
    @friends = friends.sort_by { |hsh| [hsh[:is_user] ? 0:1]}
  end
  
  def bdate_in_1_week
    @title = "Friends who have birthday in 1 week"
    @friends_1_week = Person.friends_1_week(current_user)
  end
  
  def bdate_in_2_weeks
    @title = "Friends who have birthday in 2 weeks"
    @friends_2_weeks = Person.friends_2_week(current_user)
  end
  
  def bdate_in_1_month
    @title = "Friends who have birthday in 1 month"
    @friends_1_month = Person.friends_1_month(current_user)
  end
  
  def bdate_unknown
    @title = "Friends who have birthday and we don't know when"
    @friends_unknown =  Person.friends_unknown(current_user)
  end
  
  def show
    @friend = Person.find(params[:id])
    @title = "Page by #{@friend.name}"
	  @wishes = Wish.where(:owner_id => params[:id])
    @days_till_bday = days_till_bday(@friend)
    current_user.friendships.where(:friend_id => params[:id]).first.update_attribute(:wish_num, @wishes.size)
  end


  def days_till_bday(friend)
    if friend.birthday == nil then return end
    d_now = DateTime.strptime(DateTime.now.to_s[5,DateTime.now.to_s.length],'%m-%d')
    bday = DateTime.strptime(friend.birthday.to_s[5, friend.birthday.to_s.length],'%m-%d')
    if (d_now == bday)
      'сегодня'
    else
      if (bday > d_now)
        count = (bday - d_now).to_int
        '( через ' + count.to_s + ' '+ Russian.p(count,'день','дня','дней','дня') + ' )'
      else
        count = 365 - (d_now - bday).to_int
        '( через ' + count.to_s + ' '+ Russian.p(count,'день','дня','дней','дня') + ' )'
      end
    end
  end
    
end

app/views/friends/bdate_in_1_month.html.erb
<%= render 'layouts/friend_filters' %>

<% if (@friends_1_month.size != 0)  %>
<% @friends_1_month.each do |f| %>
        <div class="friends">
          <div class="friendsAvatars"><%= link_to image_tag(f.vk_avatar_url), friend_path(f)%></div>
          <div class="friendsName"><%= f.name %></div>
          <% if f.is_user == true %>
              <%= image_tag("UserInSystem18.png",:class=>"userInSystem" ) %>
          <% end %>
        </div>
<% end %>
<% else %>
    <p>friendlist is empty</p>
<% end %>

app/views/friends/bdate_in_1_week.html.erb
<%= render 'layouts/friend_filters' %>

<% if (@friends_1_week.size != 0)  %>
<% @friends_1_week.each do |f| %>
        <div class="friends">
          <div class="friendsAvatars"><%= link_to image_tag(f.vk_avatar_url), friend_path(f)%></div>
          <div class="friendsName"><%= f.name %></div>
          <% if f.is_user == true %>
              <%= image_tag("UserInSystem18.png",:class=>"userInSystem" ) %>
          <% end %>
        </div>
<% end %>
<% else %>
    <p>friendlist is empty</p>
<% end %>

app/views/friends/bdate_in_2_weeks.html.erb
<%= render 'layouts/friend_filters' %>

<% if (@friends_2_weeks.size != 0)  %>
<% @friends_2_weeks.each do |f| %>
        <div class="friends">
          <div class="friendsAvatars"><%= link_to image_tag(f.vk_avatar_url), friend_path(f)%></div>
          <div class="friendsName"><%= f.name %></div>
          <% if f.is_user == true %>
              <%= image_tag("UserInSystem18.png",:class=>"userInSystem" ) %>
          <% end %>
        </div>
<% end %>
<% else %>
    <p>friendlist is empty</p>
<% end %>

app/views/friends/bdate_unknown.html.erb
<%= render 'layouts/friend_filters' %>

<% if (@friends_unknown.size != 0)  %>
<% @friends_unknown.each do |f| %>
        <div class="friends">
          <div class="friendsAvatars"><%= link_to image_tag(f.vk_avatar_url), friend_path(f)%></div>
          <div class="friendsName"><%= f.name %></div>
      <% if f.is_user == true %>
              <%= image_tag("UserInSystem18.png",:class=>"userInSystem" ) %>
      <% end %>
    </div>
<% end %>
<% else %>
    <p>friendlist is empty</p>
<% end %>

app/views/friends/index.html.erb
<%= render 'layouts/friend_filters' %>

<% if (@friends.size != 0)  %>
<% @friends.each do |f| %>
    <div class="friends">
        <div class="friendsAvatars"><%= link_to image_tag(f.vk_avatar_url), friend_path(f)%></div>
        <div class="friendsName"><%= f.name %></div>
      <% if f.is_user == true %>
          <%= image_tag("UserInSystem18.png",:class=>"userInSystem" ) %>
      <%= f.wishes.size - current_user.friendships.where(:friend_id => f.id).first.wish_num unless 
      (f.wishes.size - current_user.friendships.where(:friend_id => f.id).first.wish_num) == 0 %>
      <% end %>
    </div>
<% end %>
<% else %>
    <p>friendlist is empty</p>
<% end %>

app/views/friends/show.html.erb
<%= image_tag(@friend.vk_avatar_url, :class => 'FriendAvatar')%>
<div class="FriendInformation">

  <%= render 'layouts/friend_info'  %>

<p>
  <% if @friend.is_user == true %>
  <br />
      <%  if (@wishes.size != 0)  %>
          <div id="container">
            <%@wishes.each do |w| %>
                <%= link_to image_tag(w.image, :border => 0, :class => 'item'), w %>
            <% end %>
          </div>
      <% else %>
          <p>Список желаний пуст</p>
      <% end %>

  <% else%>
    Этот человек не зарегистрирован в системе
  <% end %>
</p>
</div>