config/routes.rb
Wishlist::Application.routes.draw do

  resources :wishes

  get "profile/edit"

  match '/friends', :to => 'friends#index'
  match '/friends/:id', :to => 'friends#show', :as => 'friend'
  match '/home',  :to => 'landing#home_page'
  match '/auth/vkontakte/callback', :to => 'landing#login'
  match '/logout', :to => 'landing#logout'
  match '/friends_whose_birthday_is_in_one_week', :to => 'friends#bdate_in_1_week', :as => 'friends_one_week'
  match '/friends_whose_birthday_is_in_two_weeks', :to => 'friends#bdate_in_2_weeks', :as => 'friends_two_weeks'
  match '/friends_whose_birthday_is_in_one_month', :to => 'friends#bdate_in_1_month', :as => 'friends_one_month'
  match '/friends_whose_birthday_is_unknown', :to => 'friends#bdate_unknown', :as => 'friends_unknown'
  match '/search', :to => 'wishes#search', :as => 'search'
  match '/new', :to => 'wishes#new'
  match '/reserve', :to => 'reserve#index', :as => 'reserve_index'
  match '/reserve/:id/add', :to => 'reserve#add_reserve', :as => 'add_reserve'
  match '/reserve/:id/delete', :to => 'reserve#delete_reserve', :as => 'delete_reserve'
  match '/local_login', :to => 'landing#local_login', :as => 'local_login'
  match '/local_login/:id', :to => 'landing#local_login_as', :as => 'local_user'

  root :to => 'landing#home_page'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def login
    @title = "Welcome"
	  auth_hash = request.env['omniauth.auth']
	  @app = VkontakteApi::Client.new( auth_hash.credentials.token )
	  friends_hashes = @app.friends.get( fields: 'uid, first_name, last_name, bdate, photo_max' )
	  user_hash = @app.users.get( uids: auth_hash.uid, fields: 'photo_max' ).first
	  @person = Person.find_for_vkontakte_oauth( auth_hash, friends_hashes, user_hash ) 

    if @person.persisted?
      session[:current_user_id] = @person.id
      flash[:notice] = "authentication success"
      render "login"
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end


  def home_page
    if (current_user)
      @title = "Welcome, dear #{current_user.name}";
    else
      @title = "Welcome, dear guest!"
    end
  end

  def logout
    @_current_user = session[:current_user_id] = nil
    redirect_to root_path
  end

end

app/views/landing/home_page.html.erb
<h1><%= @title %></h1>
<div class="slider">
  <div class="wrapper">
    <div id="slides">
      <div class="slides_container">
        <div>
            <%= image_tag("1.png") %>
        </div>
        <div>
          <%= image_tag("2.png") %>
        </div>
        <div>
          <%= image_tag("3.png") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/landing/local_login.html.erb
<% if Rails.env == "development" %>
     <h3>Please select which person want you login as</h3>
 <% @local_user.all.each do |u| %>
   <%= link_to u.name, local_user_path(u)  %><br />
 <% end %>
<% else %>
    <p>This page is not available in this mode</p>
<% end %>

app/views/landing/login.html.erb
<script type="text/javascript">
  if(window.opener) {
    window.opener.location.reload(true);
    window.close()
  }
</script>

app/views/landing/not_login.html.erb
<h1>Please, login before using our application</h1>