config/routes.rb
Wishlist::Application.routes.draw do

  resources :wishes

  get "profile/edit"

  match '/friends', :to => 'friends#index'
  match '/friends/:id', :to => 'friends#show', :as => 'friend'
  match '/home',  :to => 'landing#home_page'
  match '/auth/vkontakte/callback', :to => 'landing#login'
  match '/logout', :to => 'landing#logout'
  match '/friends_whose_birthday_is_in_one_week', :to => 'friends#bdate_in_1_week', :as => 'friends_one_week'
  match '/friends_whose_birthday_is_in_two_weeks', :to => 'friends#bdate_in_2_weeks', :as => 'friends_two_weeks'
  match '/friends_whose_birthday_is_in_one_month', :to => 'friends#bdate_in_1_month', :as => 'friends_one_month'
  match '/friends_whose_birthday_is_unknown', :to => 'friends#bdate_unknown', :as => 'friends_unknown'
  match '/search', :to => 'wishes#search', :as => 'search'
  match '/new', :to => 'wishes#new'
  match '/reserve', :to => 'reserve#index', :as => 'reserve_index'
  match '/reserve/:id/add', :to => 'reserve#add_reserve', :as => 'add_reserve'
  match '/reserve/:id/delete', :to => 'reserve#delete_reserve', :as => 'delete_reserve'
  match '/local_login', :to => 'landing#local_login', :as => 'local_login'
  match '/local_login/:id', :to => 'landing#local_login_as', :as => 'local_user'

  root :to => 'landing#home_page'

end

app/views/layouts/_friend_filters.html.erb
<div class="friendslink" align="center">
  <%= link_to 'Все', friends_path, :class => friends_menu_class('index') %>
  <%= link_to '1 неделя', friends_one_week_path, :class => friends_menu_class('bdate_in_1_week')  %>
  <%= link_to '2 недели', friends_two_weeks_path, :class => friends_menu_class('bdate_in_2_weeks') %>
  <%= link_to 'Месяц', friends_one_month_path, :class => friends_menu_class('bdate_in_1_month') %>
  <%= link_to 'Дата неизвестна', friends_unknown_path, :class => friends_menu_class('bdate_unknown') %>
</div>
</br>

app/views/layouts/_friend_info.html.erb
<p><%= @friend.name %></p>
<p><%=link_to 'http://vk.com/id' + @friend.vk_id,'http://vk.com/id' + @friend.vk_id  %></p>
<p>
  День рождения:
  <% if @friend.birthday != nil %>
      <%= @friend.birthday.day %> /
      <%= @friend.birthday.month %>
      <% if @friend.birthday.year < 2012 %>
          / <%= @friend.birthday.year %>
      <% end %>
      <%= @days_till_bday %>
  <% else %>
      дата неизвестна
  <% end %>
</p>

app/views/layouts/_wish_form.html.erb
<div class="mbs"><label>Хочу на ... </label><div class="stars">
  <%= f.radio_button :rating, "1", :class => "star", :checked => "checked" %>
  <%= f.radio_button :rating, "2", :class => "star" %>
  <%= f.radio_button :rating, "3", :class => "star" %>
  <%= f.radio_button :rating, "4", :class => "star" %>
  <%= f.radio_button :rating, "5", :class => "star" %></div>
  <!--<span id="error_rating"></span>--><br></div>
<div class="mbs"><label>URL</label><%=  f.text_field :url %><!--<span id="error_url"></span>--><br></div>
<div class="mbs"><label>Описание</label><%=  f.text_area :description %><br></div>
<%=  f.submit :value => "", :id => "submit", :class => "submit" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
<header class="mbl">
	<div class="row">
        <div class="col4of6">
	        <div class="row">
  		        <div class="col1of4">
                 <%= link_to image_tag("logo.png", :border => 0), root_path, :class=>"logo" %>
       	        </div>
   	 	        <div class="col3of4">
			        <nav class="h2">
                    <%= link_to "Добавить желание", search_path, :class => top_menu_class(:add_wish) %>
    			    <%= link_to "Мои желания", wishes_path, :class => top_menu_class(:list_wishes)  %>
   			    	<%= link_to "Друзья", friends_path, :class => top_menu_class(:friends) %>
    			    <%= link_to "Резерв", reserve_index_path, :class=> top_menu_class(:reserve) %>
			        </nav>
  		        </div>
	        </div>
        </div>
        <div class="col2of6">
          <div class="avatar">
            <div class="name h3">
              <%if current_user%>
              <%= image_tag current_user.vk_avatar_url, :class=>"photo" %>
              <%= current_user.name %>
            </div>
              <%= link_to image_tag("exit.png", :border => 0), {:controller => "landing", :action => "logout"},:class=>"exit" %>
              <%else%>
                      <%= link_to 'Login', 'auth/vkontakte', :class => "popup", :"data-width" => 600, :"data-height" => 400%>
              <%end%>
           </div>
        </div>
	</div>
  <div class="polosa"></div>
</header>
<%= yield %>
<div class="pusher"></div>
</div>
<footer>
  <div class="polosaF"></div>
  <div class="row">
    <div class="col1of2">
        <div>&copy; 2013 Майвиш</div>
    </div>
    <div class="col1of2">
      <div class="contacts">
        <div class="adminmywish"></div>
		<%= link_to image_tag("vkontakte.png", :border => 0), "http://www.vk.com/",:class=>"vkontakte" %>
		<%= link_to image_tag("twitter.png", :border => 0), "http://www.twitter.com/" %>
      </div>
    </div>
  </div>
</footer>

</body>
</html>